docs/AboutUs.md
=> Add Abi's details to AboutUs.md

docs/AboutUs.md
Add Hua Zhi's details to the AboutUs page
Resolves #14
=> Add Hua Zhi's profile to About Us section

docs/AboutUs.md
=> Add Yuexi's details to the AboutUs page

README.md, docs/_config.yml
=> Do tasks A2, A3, A4, B

src/main/java/seedu/address/model/module/ModuleCode.java, src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/model/person/PersonTest.java
=> Add modules field to Person

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/model/person/Link.java, src/main/java/seedu/address/model/person/Person.java, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Fix testing

src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/test/java/seedu/address/logic/commands/FindModCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/FindModCommandParserTest.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Fix errors and add tests

src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/model/person/MajorTest.java, src/test/java/seedu/address/model/person/ModContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/model/person/YearTest.java, src/test/java/seedu/address/model/tag/TagTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Add More Tests for Major, Year, Person, Tag

src/test/java/seedu/address/model/person/LinkTest.java
=> Add initial tests for Link

src/main/java/seedu/address/logic/Messages.java
=> Fix messages to include link

docs/UserGuide.md
=> Update User guide image

src/test/java/seedu/address/model/person/LinkTest.java
=> Test link extraction

build.gradle, src/main/java/seedu/address/logic/commands/EditCommand.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java
=> Edit command enhanced

src/main/java/seedu/address/logic/commands/FindModCommand.java, src/main/java/seedu/address/logic/parser/FindModCommandParser.java, src/main/java/seedu/address/model/person/ModContainsKeywordsPredicate.java
=> Add documentation

docs/UserGuide.md, src/main/java/seedu/address/logic/Messages.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/Extensions.css, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/logic/MessagesTest.java
=> Update GUI to match NUSMods

src/main/java/seedu/address/model/person/Link.java
=> Verify module codes within link validation

src/main/resources/view/Extensions.css
=> Fix empty cells

src/main/java/seedu/address/ui/PersonCard.java
=> Update show schedule button

src/main/java/seedu/address/model/person/Link.java, src/test/java/seedu/address/model/person/LinkTest.java
=> Fix bug from multiple TA slots of the same module

src/main/java/seedu/address/logic/commands/FindModCommand.java, src/main/java/seedu/address/logic/parser/FindModCommandParser.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/FindModCommandParserTest.java
=> Fix findMod

docs/UserGuide.md
=> Add quotation marks to quick guide

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/commands/FindModCommand.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/commands/FindModCommandTest.java
=> Fix person message

src/main/java/seedu/address/model/mod/ModuleCode.java, src/main/java/seedu/address/ui/PersonCard.java
=> Fix Grammar Mistake and Checkstyle Error

src/main/java/seedu/address/model/person/Link.java, src/test/java/seedu/address/model/person/LinkTest.java
=> Process hidden modules properly

src/main/java/seedu/address/model/mod/ModuleCode.java, src/main/java/seedu/address/model/person/Link.java, src/test/java/seedu/address/logic/commands/FindModCommandTest.java, src/test/java/seedu/address/model/mod/ModCodeTest.java, src/test/java/seedu/address/model/person/LinkTest.java
fixes #175, fixes #180, fixes #156 , fixes #151
=> Fix findMod bugs

docs/DeveloperGuide.md
Fix #193, #185, #195, #196, #197
=> Update DG manual testing instructions, user stories,

docs/DeveloperGuide.md
=> Add link verification enhancement to DG

docs/DeveloperGuide.md, src/test/java/seedu/address/logic/commands/FindModCommandTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Fix developer guide
